---

- name: docker_compose | Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: '/usr/bin/docker-compose'
    mode: '0755'
    owner: 'root'
    group: 'root'

