---

- name: flask_website_docker | Install Flask
  pip:
    name: flask
    state: present

- name: flask_website_docker | Create deploy directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ app_deploy_path }}"
    - "{{ app_deploy_path }}/templates"


- name: flask_website_docker | Deploy all config files
  block:

    - name: flask_website_docker | Deploy all config files | Copy
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { 'src': 'docker/Dockerfile', 'dest': "{{ app_deploy_path }}" }
        - { 'src': 'docker/requirements.txt', 'dest': "{{ app_deploy_path }}" }
        - { 'src': 'html/index.html', 'dest': "{{ app_deploy_path }}/templates" }
    
    - name: flask_website_docker | Deploy all config files | Template
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { 'src': 'docker/app.py', 'dest': "{{ app_deploy_path }}" }
        - { 'src': 'docker/docker-compose.yml', 'dest': "{{ app_deploy_path }}" }

- name: flask_website_docker | Run the app
  shell:
    cmd: |
      /usr/bin/docker-compose up -d
  args:
    chdir: "{{ app_deploy_path }}"
  become: True

